version: '3.8'  # Specify the Docker Compose file version

services:
  citroen-api-dashboard:
    image: citroen-api-dashboard-image  # Specify the Docker image to use
    build:
      context: .  # Docker context set to the current directory
    ports:
      - "127.0.0.1:8081:3033"  # Bind port 8080 of the host to port 3033 of the container
    restart: unless-stopped  # Container restart policy
    networks:
      - network-citroen-api-dashboard  # Connects the service to the specified network
    volumes:
      - box:/app/public/uploads  # Mount the 'box' volume to '/app/public/uploads'

volumes:
  box:
    driver: local  # Use local storage for the volume

networks:
  network-citroen-api-dashboard:
    driver: bridge  # Specifies that the network uses the bridge driver

